LIBOBJS = 1.o 2.o
all : test
test : test.o libabc.a
	$(CC)  -static  -o  $@  test.o  -L.  -labc
libabc.a : $(LIBOBJS)
	ar  ruv  $@  $(LIBOBJS)
test.o : test.c test.h
1.o : 1.c
2.o : 2.c
.c.o :
	$(CC)  -c  $<
clean :
	rm  -f  test  *.o  *.a  *.so